package org.problems.strings;

/**
 * https://leetcode.com/problems/find-the-difference/
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input: s = "abcd" t = "abcde"
 * 
 * Output: e
 * 
 * Explanation: 'e' is the letter that was added.
 * 
 */
public class FindDifference {

	public static char findTheDifference(String s, String t) {
		
		int[] letters = new int[26];
		for (int i = 0; i < s.length(); i++) {
			letters[s.charAt(i)-'a']++;
		}
		for (int i = 0; i < t.length(); i++) {
			letters[t.charAt(i)-'a']--;
		}
		for (int i = 0; i < 26; i++) {
			if (letters[i] == -1) {
				return (char)('a'+i);
			}
		}
		
		return 'a';
        
    }

	public static void main(String[] arg) {

		System.out.println(findTheDifference("abcd","abcde"));

	}
}
